name: Upload to S3

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Set up JDK 8
              uses: actions/setup-java@v2
              with:
                  java-version: "8"
                  distribution: "adopt"
                  server-id: "ossrh"
            - name: Bump Version and Build Artifact
              run: mvn unleash:perform-tycho -B -Dunleash.releaseArgs="jarsigner.skip=true, skipTests=true" -Dunleash.versionUpgradeStrategy=DEFAULT -Dworkflow=customWorkflow -Dunleash.scmUsername=${{ secrets.GITHUBUSERNAME }} -Dunleash.scmPassword=${{ secrets.GITHUB_TOKEN }}
              env:
                  GITHUB_TOKEN: ${{ github.token }}
                  GITHUB_USERNAME: ${{ github.username }}
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
                  aws-region: ap-east-1
            - name: Upload to s3 bucket
              run: aws s3 sync ./updatesite/target/repository/plugins s3://contrast-eclipse-plugin
