name: Upload to S3

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: 'ossrh'
    - name: Bump Version
      run: mvn unleash:perform-tycho -B -Dunleash.versionUpgradeStrategy=DEFAULT -Dunleash.releaseArgs=jarsigner.skip=true
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Clean
      run: cd targets && mvn clean verify
    - name: Build Artifact
      run: cd .. && mvn clean verify -Djarsigner.skip=true -DskipTests
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        aws-region: ap-east-1
    - name: Upload to s3 bucket
      run: aws s3 sync ./updatesite/target/repository/plugins s3://contrast-eclipse-plugin       