# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: 'ossrh'
    - name: Build with Maven
      run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Djarsigner.skip=true -B -V

    - name: Publish
      run: mvn clean integration-test -Djarsigner.skip=true && mvn clean compile package -Djarsigner.skip=true
      env:
        GITHUB_TOKEN: ${{ github.token }}
